name: emojivoto-voting-svc
namespace: apps
# TODO: Change this to the id given to you by "riser apps new emojivoto-voting-svc"
id: bab2d0e1
image: buoyantio/emojivoto-voting-svc
environment:
  GRPC_PORT: 8080
expose:
  protocol: http2
  containerPort: 8080