apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: riser-system
data:
  POSTGRES_DB: riserdb
  POSTGRES_USER: riseradmin
  POSTGRES_PASSWORD: riserpw
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: riser-system
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: riser-system
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.4-alpine
        envFrom:
          - configMapRef:
              name: postgres
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi