name: testdummy
namespace: apps
# TODO: Update the id  provided by Riser
id: 91d10594-7083-425a-ad93-fe5099348d52
image: tshak/testdummy
healthcheck:
  path: /health
expose:
  containerPort: 8000
autoscale:
  min: 0

environmentOverrides:
  prod:
    autoscale:
      min: 2

