name: testdummy
namespace: apps
# TODO: Update the id to the one provided by your riser instance
id: 59400add
image: tshak/testdummy
replicas: 2
healthcheck:
  path: /health
expose:
  containerPort: 8000

stages:
  dev:
    replicas: 1

