---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: riser-e2e
  namespace: riser-e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: riser-e2e-cluster-admin
subjects:
- kind: ServiceAccount
  name: riser-e2e
  namespace: riser-e2e
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: riser-e2e
  namespace: riser-e2e
spec:
  template:
    metadata:
      labels:
        app: riser-e2e
      annotations:
        # Required for access to the apiserver in strict istio configurations
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "${APISERVERIP}/32"
    spec:
      serviceAccountName: riser-e2e
      activeDeadlineSeconds: 600
      containers:
      - name: riser-e2e
        image: ${RISERE2EIMAGE}
        command: ["sh", "-c", "go test -count=1 -parallel=2 -tags=e2e -v ./pkg/e2e"]
        env:
        - name: RISER_APIKEY
          valueFrom:
            secretKeyRef:
              key: RISER_APIKEY
              name: riser-e2e
              optional: false
      restartPolicy: Never
  backoffLimit: 0
