name: emojivoto
namespace: apps
# TODO: Change this to the id given to you by "riser apps new emojivoto"
id: 6dbebf2a
image: buoyantio/emojivoto-web
env:
  WEB_PORT: 80
  # Note that even though the expose.containerPort is set to 8080 for the emoji and voting services, that they're exposed on port 80 internally (443 externally)
  EMOJISVC_HOST: emojivoto-emoji-svc.apps.svc.cluster.local:80
  VOTINGSVC_HOST: emojivoto-voting-svc.apps.svc.cluster.local:80
  INDEX_BUNDLE: dist/index_bundle.js
expose:
  containerPort: 80
